//! VERSION 1
/* eslint-disable no-restricted-globals */

import { precacheAndRoute } from "workbox-precaching";

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

self.importScripts("cache-pwa.js", "handle-push-notificaitons.js");
