export const Timetable = {
  LECTURE: 0,
  TUTORIAL: 1,
  LABORATORY: 2,
  ONLINE_LIVE_EVENT: 3,
  ACTIVITIES: ["Lecture", "Tutorial", "Laboratory", "Online Live Event"],
  CSU33081: 0,
  CSU33012: 1,
  CSU34016: 2,
  CSU33031: 3,
  CSU34011: 4,
  MODULE_CODES: ["CSU33081", "CSU33012", "CSU34016", "CSU33031", "CSU34011"],
  DAYS: ["mon", "tue", "wed", "thu", "fri"],
};

const timetableJSON = {
  mon: [
    {
      moduleCode: "CSU33081",
      module: "Computational Mathematics",
      lecturer: "Éamonn Ó Nualláin",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    {
      moduleCode: "CSU33012",
      module: "Software Engineering",
      lecturer: "Edmond Stephen Barrett",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    {
      moduleCode: "CSU34016",
      module: "Introduction To Functional Programming",
      lecturer: "Andrew Butterfield",
      activity: Timetable.TUTORIAL,
      isOnline: false,
      classroom: "L2.01/L2.02",
    },
    {
      moduleCode: "CSU33012",
      module: "Software Engineering",
      lecturer: "Edmond Stephen Barrett",
      activity: Timetable.TUTORIAL,
      isOnline: true,
      classroom: "Blackboard",
    },
    {
      moduleCode: "CSU33031",
      module: "Computer Networks",
      lecturer: "Stefan Weber",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    undefined,
    {
      moduleCode: "CSU33031",
      module: "Computer Networks",
      lecturer: "Stefan Weber",
      activity: Timetable.LABORATORY,
      isOnline: true,
      classroom: "Blackboard",
    },
    {
      moduleCode: "CSU33031",
      module: "Computer Networks",
      lecturer: "Stefan Weber",
      activity: Timetable.TUTORIAL,
      isOnline: true,
      classroom: "Blackboard",
    },
    undefined,
  ],
  tue: [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    {
      moduleCode: "CSU34011",
      module: "Symbolic Programming",
      lecturer: "Rafael Timothy Fernando",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    {
      moduleCode: "CSU33031",
      module: "Computer Networks",
      lecturer: "Stefan Weber",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    {
      moduleCode: "CSU34011",
      module: "Symbolic Programming",
      lecturer: "Rafael Timothy Fernando",
      activity: Timetable.TUTORIAL,
      isOnline: false,
      classroom: "LG35/LG36",
    },
    undefined,
  ],
  wed: [
    undefined,
    undefined,
    undefined,
    {
      moduleCode: "CSU34016",
      module: "Introduction To Functional Programming",
      lecturer: "Andrew Butterfield",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    undefined,
    undefined,
    undefined,
    {
      moduleCode: "CSU33081",
      module: "Computational Mathematics",
      lecturer: "Éamonn Ó Nualláin",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    {
      moduleCode: "CSU33012",
      module: "Software Engineering",
      lecturer: "Edmond Stephen Barrett",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
  ],
  thu: [
    undefined,
    undefined,
    undefined,
    undefined,
    {
      moduleCode: "CSU33081",
      module: "Computational Mathematics",
      lecturer: "Éamonn Ó Nualláin",
      activity: Timetable.ONLINE_LIVE_EVENT,
      isOnline: true,
      classroom: "Blackboard",
    },
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  fri: [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    {
      moduleCode: "CSU34016",
      module: "Introduction To Functional Programming",
      lecturer: "Andrew Butterfield",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    {
      moduleCode: "CSU34011",
      module: "Symbolic Programming",
      lecturer: "Rafael Timothy Fernando",
      activity: Timetable.LECTURE,
      isOnline: true,
      classroom: "Blackboard",
    },
    undefined,
    undefined,
  ],
};

export default timetableJSON;
